- .azure-pipelines.yaml
- .pre-commit-config.yaml
- environment.yml
Just noticed that the pre-commit checks are missing for CI and that we want to check our documentation.
> Added pre-commit to CI and doc8 to pre-commits.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- CHANGES.rst
- README.rst
- docs/conf.py
> Add issue and pull request templates.

- CODE_OF_CONDUCT.rst
- docs/code-of-conduct.rst
- docs/index.rst
- tox.ini
> Provisional Code of Conduct.

- gettsim/data/param.yaml
If merged the commits in this PR reorder the parameters by groups.
Current groups are:
- alg2
- sgbxii
- kiz
- uhv
- alg
- alh
- sh
- soc_ins_contrib
- eg
- elg
- kinderfreibetrag
- kindergeld
- zve
- abgeltung
- tax_sched
- tarif
- wohngeld
- rente
- ust
- other
> Reorder keys by groups in param.yaml.

- .codecov.yml
> Ignore files while testing coverage.

- environment.yml
- meta.yaml
> Add pytest to runtime dependencies.

- CHANGES.rst
- docs/conf.py
- docs/index.rst
Update changes.rst after the fact.
> Update changes.rst for 0.2.0

- CHANGES.rst
- docs/changes.rst
- docs/conf.py
- docs/how-to-contribute.rst
- docs/how-to-maintain.rst
- docs/index.rst
- environment.yml
- setup.cfg
Backport #51.
* Add maintenance manual.
* Update changelog and include in docs.
> Add maintenance manual. (#51)

- docs/how-to-maintain.rst
Two adjustments to the maintenance manual
- Delete the note on labels for backport PRs
- longer names for backport branches
> Update maintenance manual.

- docs/how-to-maintain.rst
> Update maintenance manual. (#98)

- .azure-pipelines.yaml
- gettsim/tests/test_alg2.py
> Fix silent errors on Azure.

- CHANGES.rst
- docs/conf.py
- gettsim/__init__.py
- setup.cfg
- setup.py
- Add release notes.
- Bump version numbers.
> Prepare release of 0.2.1

- CHANGES.rst
- docs/conf.py
- gettsim/__init__.py
- setup.cfg
- setup.py
> Prepare release of 0.2.1. (#107)

- gettsim/data/param.yaml
The group names of the variables are not self-explanatory at the moment. We rename the groups according to https://github.com/iza-institute-of-labor-economics/gettsim/issues/79#issuecomment-554283492
> Rename groups in params.yaml.

- README.rst
- docs/index.rst
Improve the wording on the landing pages of docs / github.
> Small updates to text on landing page.

- README.rst
- docs/how-to-contribute.rst
#141 left out some changes.
- New CI status badge in README
- Removed last mention of Azure in docs.
> Update badges and remove last pieces of Azure.

- gettsim/benefits/unterhalt.py
- gettsim/data/kindergeld.yaml
- gettsim/pre_processing/policy_for_date.py
- gettsim/taxes/kindergeld.py
Regroup Kindergeld params according to #148 and adjusted code accordingly.
> regroup kindergeld

- gettsim/benefits/arbeitsl_geld.py
- gettsim/benefits/elterngeld.py
- gettsim/data/arbeitsl_geld.yaml
- gettsim/data/wohngeld.yaml
- gettsim/pre_processing/policy_for_date.py
> Regroup alg

- data_not_implemented/unterhalt.yaml
- gettsim/benefits/unterhalt.py
- gettsim/data/unterhalt.yaml
- gettsim/pre_processing/policy_for_date.py
Regroup unterhalt parameters and outsource unused ones.
> Regrouping Unterhalt

- gettsim/dag.py
- gettsim/tests/test_dag.py
- setup.cfg
Please check whether this makes sense, previous formatting would be a problem for many entries.
I cared more about the look of the error message to the user than flake8 being happy here; need to find a workaround still.
> Add error messages for conflicts between functions and data and data and user_columns.

- .pre-commit-config.yaml
- docs/conf.py
- gettsim/_numpy.py
- gettsim/benefits/arbeitsl_geld.py
- gettsim/benefits/arbeitsl_geld_2.py
- gettsim/pre_processing/generic_functions.py
- gettsim/pre_processing/piecewise_functions.py
- gettsim/taxes/eink_st.py
- gettsim/taxes/soli_st.py
- gettsim/tests/test_soli_st.py
- setup.cfg
The function `piecewise_polynomial` only supports scalars as inputs for `x`. This PR enables the function to accept arrays and scalars.
> Vectorize piecewise_polynomial.

- CHANGES.rst
- gettsim/dag.py
- gettsim/interface.py
- gettsim/tests/test_interface.py
> Check if root nodes are missing.

- docs/variables.rst
- gettsim/benefits/benefit_checks/benefit_checks.py
- gettsim/benefits/benefit_checks/vermoegens_checks.py
- gettsim/benefits/kinderzuschlag/kinderzuschlag.py
- gettsim/benefits/kinderzuschlag/kinderzuschlag_eink.py
- gettsim/benefits/kinderzuschlag/kost_unterk.py
- gettsim/taxes/abgelt_st.py
- gettsim/taxes/eink_st.py
- gettsim/taxes/favorability_check.py
- gettsim/taxes/kindergeld.py
- gettsim/taxes/soli_st.py
- gettsim/taxes/zu_verst_eink/eink.py
- gettsim/taxes/zu_verst_eink/freibetraege.py
- gettsim/taxes/zu_verst_eink/vorsorge.py
- gettsim/taxes/zu_verst_eink/zu_verst_eink.py
We want to insert type hints for the rest of the modules.
> Complete docstrings in rest of module.

- docs/gettsim_objects/params.rst
- setup.py
…align to new names of directories.
> Fixed renaming bugs.

- gettsim/parameters/arbeitsl_geld_2.yaml
implements 2021 changes in ALG2 Regelbedarfe
> 2021 ALG2 regelbedarfe

- gettsim/parameters/unterhalt.yaml
Mindestunterhalt has been raised effective 2021 before the 2019 reform actually became effective.
> Raise in Mindestunterhalt

- gettsim/policy_environment.py
- gettsim/transfers/wohngeld.py
closes #255. Nothing magical happening here.
> Wohngeld function renaming

- gettsim/parameters/wohngeld.yaml
- gettsim/policy_environment.py
- gettsim/transfers/benefit_checks/vermoegens_checks.py
> Paramaterize Wohngeld Wealth Check

- docs/gettsim_objects/variables_out.rst
fix kinderzuschlag variable in doku
> fixed kinderzuschlag in documentation.

- gettsim/tests/test_arbeitsl_geld.py
- gettsim/tests/test_eink_st.py
- gettsim/tests/test_elterngeld.py
- gettsim/tests/test_vorsorge.py
- gettsim/tests/test_zu_versteuerndes_eink.py
- setup.cfg
> take care of deprecation warnings in tests

- docs/gettsim_developer/how-to-contribute.rst
> restructured how to contribute in documentation.

- gettsim/parameters/ges_renten_vers.yaml
- gettsim/transfers/rente.py
Used parameters for regelaltersgrenze. Closes #304.
> Used parameters for regelaltersgrenze

- gettsim/parameters/ges_renten_vers.yaml
- gettsim/parameters/grunds_ia.yaml
Updated the documentation of the parameters in the parameter files grunds_ia.yaml and ges_renten_vers.yaml.
> Updated parameter files grunds_ia.yaml and ges_renten_vers.yaml

- gettsim/transfers/benefit_checks/vermoegens_checks.py
- gettsim/transfers/kinderzuschlag/kinderzuschlag.py
- gettsim/transfers/unterhalt.py
Remove modifications of arguments within functions at several places.
This fixes part of #272, but doesn't implement an enforcement mechanism yet as discussed in that issue.
> Remove modifications of arguments within functions.

- CHANGES.rst
- docs/geps/gep-00.rst
- docs/gettsim_developer/how-to-maintain.rst
Trivial updates and clarifications for parts where I stumbled when setting up 0.4.2
> Update docs on release process

- docs/gettsim_developer/how-to-contribute.rst
- environment.yml
Directly run `pip install -e .` as part of `conda env create`
> Set up development environment as part of installation.

- dashboard/app/main.py
- dashboard/pre_processing_data.py
- setup.cfg
Closes #363 
pytest would import the dashboard code, which sets up the data in cwd. However, it is present in the dashboard directory already. Just doing a try/except to pick the right one.
> Speed up tests

- .conda/meta.yaml
- CHANGES.rst
- docs/conf.py
- docs/gettsim_developer/how-to-contribute.rst
- gettsim/__init__.py
- setup.cfg
- setup.py
- Some fixes before the release
- Also added one additional bullet point to "How To Contribute"
> Release v0.5.0

- gettsim/parameters/arbeitsl_geld_2.yaml
- gettsim/parameters/grunds_im_alter.yaml
- gettsim/parameters/kinderzuschl.yaml
- gettsim/transfers/grunds_im_alter.py
Some visual adjustments for paramter files
> Some visual adjustments for paramter files

- gettsim/parameters/soz_vers_beitr.yaml
> Fix wrong parameter (#373)

- dashboard/app/main.py
- dashboard/pre_processing_data.py
When trying to create data for the parameter dashboard, it turned out that one health insurance parameter was not appropriately named.
In addition, I added a comment on what to do if the data are not there
> Fix parameter dashboard

- dashboard/app/main.py
- Pytest raises an error when looking for tests and the input data for the dashboard (`param_dashboard_data.pickle`) is missing.
- Bokeh expects the code for the dashboard in the script without a `if __name__ == '__main__':` condition.
Solution: raise warning if input data is missing instead of raising an error.
> raise warning (instead of error) if data for dashboard is missing.

- .pre-commit-config.yaml
- gettsim/config.py
- gettsim/tests/test_aggregation_functions.py
- gettsim/transfers/elterngeld.py
Add several new pre-commit hooks.
Make changes to code base which have been detected by the new hooks.
Some hooks that are not yet running through are commented out for now.
> Add new pre-commit hooks

- src/_gettsim/functions_loader.py
- src/_gettsim/interface.py
- src/_gettsim/shared.py
I also like the suggested notation, so I made the requested changes.
Closes #489
> fix b028 error in f-strings.

- src/_gettsim/parameters/ges_rente.yaml
- src/_gettsim/transfers/rente.py
Reference the issue or discussion, if there is any. Provide a description and/or bullet
points to describe the changes in this PR.
> fixed parameter definition rente mit 63 plus notes.

- .pre-commit-config.yaml
- docs/gettsim_developer/how-to-contribute.md
> add note on utf-8 encoding under Windows.

- README.md
- docs/gettsim_developer/how-to-contribute.md
- docs/gettsim_developer/how-to-maintain.md
- docs/gettsim_developer/index.md
- docs/how_to_guides/different_ways_to_load_policy_functions.ipynb
- docs/installation.md
- setup.cfg
Will fix the second part of  #502, i.e., updating the docs on maintaining GETTSIM.
Now that publishing to PyPI worked, I realized that the keywords were in a wrong format, to update them I opened this PR even though publishing to conda-forge is not there yet.
> Update maintainer docs

- CHANGES.md
Just an update of `CHANGES.md`
> Prepare for releasing v0.7

- docs/gettsim_developer/how-to-maintain.md
- environment.yml
- setup.cfg
Small stuff that came up when releasing 0.7
> Improve docs, fix deps

- CHANGES.md
- src/_gettsim/parameters/arbeitsl_geld_2.yaml
- src/_gettsim/transfers/arbeitsl_geld_2/arbeitsl_geld_2_eink.py
- make sure `arbeitsl_geld_2_eink_anr_frei_m` uses the correct variable
- improve documentation
> make sure `arbeitsl_geld_2_eink_anr_frei_m` uses the correct variable

- CHANGES.md
- src/_gettsim/parameters/sozialv_beitr.yaml
- src/_gettsim/social_insurance_contributions/eink_grenzen.py
- src/_gettsim/social_insurance_contributions/ges_krankenv.py
Use only parameters from the beginning of a year to calculate `midijob_faktor_f`.
Closes #597
> Correct midijob_faktor_f

- CHANGES.md
- docs/gettsim_objects/input_variables.md
- src/_gettsim/config.py
- src/_gettsim/parameters/sozialv_beitr.yaml
- src/_gettsim/social_insurance_contributions/ges_pflegev.py
- src/_gettsim_tests/test_data/sozialv_beitr/2023-07/hh_id_23.yaml
- src/_gettsim_tests/test_data/sozialv_beitr/2023-07/hh_id_24.yaml
- src/_gettsim_tests/test_data/sozialv_beitr/2023-07/hh_id_25.yaml
- src/_gettsim_tests/test_data/sozialv_beitr/2023-07/hh_id_26.yaml
- src/_gettsim_tests/test_data/sozialv_beitr/2023-07/hh_id_27.yaml
Adapt calculation of `ges_pflegev_beitr_m` to new reform (Pflegeunterstützungs- und -entlastungsgesetz - PUEG)
Closes #595
> Implement reform of gesetzliche Pflegepflegeversicherung effective as of 2023-07-01

- docs/how_to_guides/visualizing_the_system.ipynb
Trivial change, which changes annoying behaviour in TOC.
> Fix heading level in notebook.

- src/_gettsim/parameters/sozialv_beitr.yaml
- src/_gettsim/social_insurance_contributions/eink_grenzen.py
- src/_gettsim/social_insurance_contributions/ges_krankenv.py
- src/_gettsim/taxes/abgelt_st.py
- src/_gettsim_tests/test_data/full_taxes_and_transfers/2008/hh_id_1.yaml
- src/_gettsim_tests/test_full_taxes_and_transfers.py
Abgeltungssteuer did not exist before 2008; make sure it is active in GETTSIM only after that date.
> Apply dates_active decorator on abgelt_st.

- .github/workflows/main.yaml
Update micromamba as explained at https://github.com/mamba-org/provision-with-micromamba#migration-to-setup-micromamba.
> Update micromamba in GHA

- .pre-commit-config.yaml
- CHANGES.md
- docs/gettsim_objects/input_variables.md
- src/_gettsim/config.py
- src/_gettsim/transfers/rente.py
- src/_gettsim_tests/test_data/grundrente_proxy_rente/2021-07-01/hh_id_1.yaml
- src/_gettsim_tests/test_data/grundrente_proxy_rente/2021-07-01/hh_id_2.yaml
- src/_gettsim_tests/test_data/grundrente_proxy_rente/2021-07-01/hh_id_3.yaml
- src/_gettsim_tests/test_data/grundrente_proxy_rente/2021-07-01/hh_id_4.yaml
- src/_gettsim_tests/test_data/grundrente_proxy_rente/2021-07-01/hh_id_5.yaml
- src/_gettsim_tests/test_data/grundrente_proxy_rente/2021-07-01/hh_id_6.yaml
- src/_gettsim_tests/test_data/grundrente_proxy_rente/2021-07-01/hh_id_7.yaml
- src/_gettsim_tests/test_data/grundrente_proxy_rente/2021-07-01/hh_id_8.yaml
- src/_gettsim_tests/test_grundrente.py
Closes #612: Introducing monthly precision in Zugangsfaktor calc
> Monthly precision in Zugangsfaktor

- src/_gettsim/transfers/elterngeld.py
> remove todo Elterngeld

- src/_gettsim/parameters/unterhaltsvors.yaml
- src/_gettsim/transfers/unterhaltsvors.py
Make sure that `altersgrenze_mindesteinkommen` can vary independently of other parameters.
> introduce paramter for Unterhaltsvorschuss altersgrenze_mindesteinkommen

- src/_gettsim/synthetic.py
- src/_gettsim_tests/test_synthetic.py
allow for up to 10 children in create_synthetic_data.
> allow for up to 10 children in create_synthetic_data.

- CHANGES.md
- src/_gettsim/social_insurance_contributions/arbeitsl_v.py
- src/_gettsim/social_insurance_contributions/beitr_bemess_grenzen.py
- src/_gettsim/social_insurance_contributions/eink_grenzen.py
- src/_gettsim/social_insurance_contributions/ges_krankenv.py
- src/_gettsim/social_insurance_contributions/ges_pflegev.py
- src/_gettsim/social_insurance_contributions/ges_rentenv.py
- src/_gettsim_tests/test_data/sozialv_beitr/2004-04-01/rentner.yaml
> Midijobfaktor calculation in 2004

- docs/tutorials/advanced_usage.ipynb
- docs/tutorials/basic_usage.ipynb
- environment.yml
Adjusted the environment.yaml from fork PR #691
> minor fixes to doc

- CHANGES.md
- src/_gettsim/synthetic.py
- src/_gettsim_tests/test_synthetic.py
Add argument to create_synthetic_data on whether adults are married.
> Add argument to create_synthetic_data on whether adults are married.

- src/_gettsim/sozialversicherung/rente/altersrente/besonders_langjährig/besonders_langjährig.py
- src/_gettsim/sozialversicherung/rente/altersrente/für_frauen/für_frauen.py
- src/_gettsim/sozialversicherung/rente/altersrente/langjährig/langjährig.py
- src/_gettsim/sozialversicherung/rente/altersrente/regelaltersrente/regelaltersrente.py
- src/_gettsim/sozialversicherung/rente/altersrente/wegen_arbeitslosigkeit/wegen_arbeitslosigkeit.py
- src/_gettsim/unterhaltsvorschuss/unterhaltsvorschuss.py
- tests/ttsim/test_compute_taxes_and_transfers.py
Noted in the process of parameter conversion that all tests pass when fake dependencies are removed. As that PR is going to be large, I move this out to a separate one.
> Remove fake dependencies, fixes #666.

- src/ttsim/__init__.py
- src/ttsim/convert_nested_data.py
- tests/ttsim/test_mettsim.py
Creates functions that make the from/to df functions available for the interface DAG.
> Make dataframe convenience functions available for TTSIM-DAG

- src/ttsim/__init__.py
- src/ttsim/interface_dag_elements/data_converters.py
- src/ttsim/interface_dag_elements/fail_if.py
- tests/ttsim/test_convert_nested_data.py
- tests/ttsim/test_end_to_end.py
- Add an end-to-end test (df-to-df in this case)
- Fail if the mapper that specifies the mapping between NestedData and df is incomplete
> Add end to end tests and fail if mapper is incomplete in results conversion

- src/_gettsim/interface.py
- src/ttsim/interface_dag.py
- src/ttsim/interface_dag_elements/data_converters.py
- src/ttsim/interface_dag_elements/input_data.py
- src/ttsim/interface_dag_elements/interface_node_objects.py
- tests/ttsim/interface_dag_elements/test_data_converters.py
- tests/ttsim/test_end_to_end.py
- tests/ttsim/test_interface_dag.py
DAG depends on input data. Allows to specify input data in different ways (nested df, df with mapper, tree).
Supersedes #975.
Todo:
> InputDependentInterfaceFunction

- src/ttsim/plot_dag.py
InputDependentInterfaceFunctions were orphaned nodes in the interface DAG, I added the nodes manually to the DAG.
> Add InputDependentInterfaceFunctions to interface DAG plot

- pixi.lock
- pyproject.toml
- src/_gettsim/lohnsteuer/lohnsteuer.py
- src/ttsim/interface_dag.py
- tests/ttsim/interface_dag_elements/test_mettsim.py
Attempt to use the fix outlined in #981.
@MImmesberger, can you please check whether this fixes the issue in the notebook you had somewhere? If possible, make a test case out of that. Thanks!
> Run fail_if functions first, closes #981

- src/ttsim/interface_dag_elements/fail_if.py
- src/ttsim/tt_dag_elements/param_objects.py
- tests/ttsim/interface_dag_elements/test_orig_policy_objects.py
- tests/ttsim/test_plot_dag.py
Closes #980 
As discussed, makes all arguments but 'value' of the params dataclasses optional.
> Upserting of params

- src/ttsim/__init__.py
- src/ttsim/interface_dag.py
- src/ttsim/interface_dag_elements/__init__.py
- src/ttsim/main_args.py
- tests/ttsim/test_end_to_end.py
- tests/ttsim/test_interface_dag.py
- Allow for dict output spec in main
- Return qnames when using AllOutputNames
> Small fixes related to #991

- CHANGES.md
- pixi.lock
- pyproject.toml
- src/_gettsim_tests/test_jittability.py
- src/_gettsim_tests/test_plot_dag.py
- src/gettsim/__init__.py
- src/gettsim/plot/__init__.py
- src/gettsim/plot/dag/__init__.py
- src/gettsim/plot_dag/__init__.py
- Change plotting of dags to future-proof namespacing
- Following some [TTSIM changes](https://github.com/ttsim-dev/ttsim/pull/11/), this PR updates the exposed plotting function and adds `NodeSelector` as an importable element.
> Updates to plotting function

- CHANGES.md
- src/gettsim/germany/einkommensteuer/abgeltungssteuer/abgeltungssteuer.py
- src/gettsim/germany/einkommensteuer/einkünfte/aus_kapitalvermögen/aus_kapitalvermögen.py
- src/gettsim/germany/einkommensteuer/einkünfte/aus_kapitalvermögen/freibeträge.yaml
- src/gettsim/germany/familie/inputs.py
- src/gettsim/germany/kinderzuschlag/einkommen.py
- src/gettsim/germany/sozialversicherung/pflege/beitrag/beitrag.py
- src/gettsim/germany/sozialversicherung/rente/wartezeit.py
- src/gettsim/tests_germany/policy_cases/einkommensteuer/betrag/2015-01-01/hh_id_2.yaml
- src/gettsim/tests_germany/policy_cases/sozialversicherung/beiträge/2025-01-01/einkommen_in_gleitzone.yaml
- Set end dates of helper functions that became unnecessary with rule changes, fixes #1079 
- Correct calculation of "Einkünfte aus Kapitalvermögen", fixes #843
> Let functions end on time; correct calculation of "Einkünfte aus Kapitalvermögen"

- .github/ISSUE_TEMPLATE/yearly_param_update.md
- CHANGES.md
- src/gettsim/germany/einkommensteuer/abzüge/sonderausgaben.yaml
- src/gettsim/germany/einkommensteuer/abzüge/vorsorge.py
- src/gettsim/germany/einkommensteuer/abzüge/vorsorge.yaml
- src/gettsim/germany/sozialversicherung/rente/beitrag/beitragsbemessungsgrenze.yaml
- src/gettsim/germany/sozialversicherung/rente/beitrag/beitragssatz.yaml
- Update max Kinderbetreuungskosten according to Jahressteuergesetz 2024
- Convert max Vorsorgeaufwendungen to a param function; compute from BBG knappschaftliche RV (West) and Beitragssatz knappschaftliche RV
- Update parameters knappschaftliche RV
> Make Vorsorgeaufwendungen a param function and update parameters of   knappschaftliche RV and Kinderbetreuungskosten in ESt
