ttsim-dev/gettsim

gettsim/policy_for_date.py, gettsim/tax_transfer.py, gettsim/tests/test_favorability_check.py, gettsim/tests/test_tax_sched.py, gettsim/tests/test_tax_transfer.py
In #61, the definition of zve_list was not moved into policy_for_date and is still assigned in each test_case. As of 2009 the Abgeltungssteuer was introduced we also need to include this in the favorability check of the different ways to calculate the income tax. For more details see #76 and #81.
=> Moving assignment zve_list to policy_for_date. 

docs/index.rst
Inclusion of README.rst in main page of docs starts one line too late.
https://gettsim.readthedocs.io/en/latest/
=> Fix off-by-one error in include statement in documentation.

.azure-pipelines.yaml
The tests on Windows did not run and reported success. See git push --set-upstream origin fix-windows-on-azure for an example.
The error was introduced in #100 when I changed from `pip install -e` to `conda develop .`. Apparently, the latter causes trouble, but I do not know why.
Azure is nice because it provides more resources than other providers, but the lack of an official support for conda is just annoying. In the long-run we should keep an eye on Github Actions which also support 10 simultaenous builds and also caches stages. This means, for example, that as long the environment is not changed, it is not recreated. This would speed up the test suite tremendously. Conda support is also premature at the moment (`https://github.com/actions/starter-workflows/issues/44`), but maybe this …
=> Fix Windows on Azure.

gettsim/data/arbeitsl_geld_2.yaml
This PR removes the parameters [ahvermiet](https://github.com/iza-institute-of-labor-economics/gettsim/blob/669a2cd585f13735b42cd0977eca7a8dbf3fb4ee/gettsim/data/arbeitsl_geld_2.yaml#L684) and [ahvzins](https://github.com/iza-institute-of-labor-economics/gettsim/blob/669a2cd585f13735b42cd0977eca7a8dbf3fb4ee/gettsim/data/arbeitsl_geld_2.yaml#L698).
closes #128
* add description and note keys
Discuss alternatives in #128
=> Remove parameters ahvermiet and ahvzins

CHANGES.rst, gettsim/data/e_st_abzuege.yaml, gettsim/taxes/zve.py
=> proper modelling of Kinderfreibetrag

docs/geps/gep-01.rst
Adds example of naming ``arbeitsl_geld`` from the discussion in #79 to the documentation in GEP 1.
=> Added example from discussion on naming arbeitsl_geld.

gettsim/pre_processing/policy_for_date.py, gettsim/tests/conftest.py
Some tests failed because they relied on params in yaml files which have not been read with the correct encoding. Use utf-8 for files containing umlauts.
FYI: @Eric-Sommer @hmgaudecker @MaxBlesch
=> Fix encoding issue with files containing umlauts.

CHANGES.rst, docs/conf.py, gettsim/__init__.py, setup.cfg, setup.py
Repeatedly calling `gettsim.test()` is not possible because there seems to be some state dependence.
Skip all other calls to the function except the first and emit a warning.
=> Release 0.3.1 and skip and emit warning if gettsim.test() is repeatedly called.

gettsim/benefits/elterngeld.py, gettsim/config.py, gettsim/interface.py, gettsim/pre_processing/policy_for_date.py, gettsim/taxes/zu_verst_eink/freibetraege.py, gettsim/tests/test_arbeitsl_geld.py, gettsim/tests/test_arbeitsl_geld_2.py, gettsim/tests/test_benefit_checks.py, gettsim/tests/test_eink_st.py, gettsim/tests/test_elterngeld.py, gettsim/tests/test_favorability_check.py, gettsim/tests/test_kindergeld.py, gettsim/tests/test_kinderzuschlag.py, gettsim/tests/test_soli_st.py, gettsim/tests/test_soz_vers.py, gettsim/tests/test_tax_transfer.py, gettsim/tests/test_unterhalt_vorschuss.py, gettsim/tests/test_vorsorge.py, gettsim/tests/test_wohngeld.py, gettsim/tests/test_zu_versteuerndes_eink.py
The docstrings in `policy_for_date.py` are either incomplete or not existent. I will complete the docstrings and refactor the code to have a more readable structure.
=> Update policy for date

gettsim/benefits/arbeitsl_geld_2/eink_anr_frei.py, gettsim/demographic_vars.py, gettsim/interface.py, gettsim/tests/test_interface.py
`kinder_in_hh_individual` did not play well with `debug=True` because it is not at the household level
- Remove as it was a one-liner used in one place only
- Add a custom error message to the interface (suggestions for improvements welcome!)
=> Fix levels of internal variables and provide helpful error message if variable with wrong level is requested as target

CHANGES.rst, gettsim/interface.py, setup.cfg
The ``targets`` passed by the user might not be unique and create duplicated columns in the output. Raise an error if it happens.
=> Add a check for non-unique targets.

.conda/meta.yaml, .github/workflows/continuous-integration-workflow.yaml, .pre-commit-config.yaml, .readthedocs.yaml, CHANGES.rst, docs/rtd_environment.yml, environment.yml, gettsim/tests/test_functions_loader.py, setup.cfg
- gettsim is now tested with Python 3.8. There had been no problems.
- gettsim also works with pandas 1.1 which caused some problems with estimagic. They changed the way to test two pandas series or dataframes only up to some precision. `check_less_precise` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_series_equal.html) is deprecated since 1.1 and replaced by atol and rtol. At some point, we should switch and set pandas 1.1 as the new lower bound.
=> Support Python 3.8.

docs/gettsim_objects/variables.rst
The list of input variables defines `kind` as `Dummy: Child by SOEP definition`. I changed that since gettsim is supposed to be agnostic of which survey is used as input.
=> Remove SOEP correspondence from Documentation

docs/gettsim_objects/variables.rst, gettsim/synthetic_data/synthetic.py
When creating synthetic data, capital income is wrongly assigned according to `bruttolohn_m` argument. This is hereby corrected
=> Fix capital income in synthetic data

CHANGES.rst, gettsim/parameters/wohngeld.yaml
A new decree updates Wohngeld parameters: Values are updated by 2,788 percent. Additional rounding rules apply.
Reference: V. v. 03.06.2021 BGBl. I S. 1369. https://offenegesetze.de/veroeffentlichung/bgbl1/2021/28#page=113
Additional Reference: https://www.bundesregierung.de/breg-de/suche/wohngeld-steigt-ab-januar-2022-1884454
Note that [_Anlage 1 (zu § 12 Absatz 1)_](https://www.buzer.de/gesetz/8380/a233450.htm) and [_Anlage 2 (zu § 19 Absatz 1)_](https://www.buzer.de/gesetz/8380/a156499.htm
) remains unchanged. This is because there is a new [§ 43](https://www.buzer.de/gesetz/8380/a156498.htm):
> 2Die erste Fortschreibung des Wohngeldes erfolgt zum 1. Januar 2022.
> 
>   (2) § 12 Absatz 4 Satz 1 findet bei der Fortschreibung des Wohngeldes keine Anwendung.
This PR implements these …
=> Add updated wohngeld parameters for 2022

docs/how_to_guides/different_ways_to_load_policy_functions.ipynb, gettsim/synthetic_data/synthetic.py, gettsim/taxes/zu_verst_eink/freibetraege.py
Pandas 1.4 leads to errors in tests due to stricter indexing rules, adds depreciation warnings for df.append(...). This PR adjusts the code to get rid of them.
=> Pandas 1.4

CHANGES.rst, docs/rtd_environment.yml, gettsim/dag.py, gettsim/interface.py, gettsim/parameters/eink_st.yaml, gettsim/parameters/ges_rentenv.yaml, gettsim/policy_environment.py, gettsim/shared.py, gettsim/taxes/favorability_check.py, gettsim/tests/test_docs.py, gettsim/tests/test_interface.py, gettsim/tests/test_rounding.py
Implement the possibility for optional rounding as specified in [GEP-05](https://gettsim--324.org.readthedocs.build/en/324/geps/gep-05.html). 
And implement optional rounding for one examplary function (`eink_st_tu`)
Addresses #88.
#316 was started earlier and will implement rounding for all Grundrente and Grundsicherung im Alter variables after this PR is merged.
- Reintroduce rounding where applicable
=> Implement optional rounding

CHANGES.rst, docs/gettsim_objects/index.rst, docs/gettsim_objects/input_variables.rst, docs/gettsim_objects/means_testing.rst
Referring to #326, the variable `vermögen_hh` was changed into `vermögen_bedürft_hh` (Vermögen für Bedürftigkeitsprüfungen). In order to understand which assets are not counted towards Vermögen for each relevant transfer, a table was created, which shall be added to the documentation of GETTSIM, as asked [here](https://github.com/iza-institute-of-labor-economics/gettsim/issues/326#issuecomment-1158598062).
=> Documentation for Vermögensbegriff

src/_gettsim/interface.py
#429 broke notebooks in the documentation and elsewhere by sorting results. 
GETTSIM should never change the ordering of rows; everything is built on the premise of those staying constant.
We may want to require users to pass sorted DataFrames only, that would be for #388 (would require that we have nested columns only).
=> Revert the sorting of results in #429 / d44c2f2a, which broke docs etc.

src/_gettsim/transfers/unterhalt.py
Produce a nicer error if `mindestunterhalt` is required before 2016, link to #479 in that message.
=> Nicer error message relating to #479

docs/tutorials/advanced_usage.ipynb, src/_gettsim/interface.py, src/_gettsim/transfers/unterhalt.py
- Noted yesterday that the advanced usage tutorial did not show all plots
- The nicer error message implemented in #480 broke tests in #425, move it to a different place (fine for now, I think).
=> Show all plots in docs, raise error outside of vectorized function

src/_gettsim/demographic_vars.py, src/_gettsim/transfers/arbeitsl_geld_2/arbeitsl_geld_2.py
Addresses issue https://github.com/iza-institute-of-labor-economics/gettsim/issues/499. Currently, for the years since 2011, children aged 18 or older receive Regelsatz 4, even tough it is specified in the law that they should receive Regelsatz (see [here](4. Personenkreis nach § 20 Abs. 2 Satz 2 SGB II, 4. Personenkreis nach § 20 Abs. 2 Satz 2 SGB II).
This bug is now fixed and probably stems from the old regulation before 2010, where the same portion of the Regelsatz was applicable for children aged 14-24.
=> address bug in Regelsatz for ALG2.

src/_gettsim/parameters/kindergeld.yaml
The recent increase in Kindergeld became valid by 2023-01-01, as stated [here](https://www.buzer.de/7_InflAusG.htm). According to the current implementation, it has been valid since 2022-01-01. This is corrected here.
=> Fix 2023 kindergeld period

src/_gettsim_tests/_helpers.py, src/_gettsim_tests/test_arbeitsl_geld.py, src/_gettsim_tests/test_arbeitsl_geld_2.py, src/_gettsim_tests/test_benefit_checks.py, src/_gettsim_tests/test_eink_st.py, src/_gettsim_tests/test_elterngeld.py, src/_gettsim_tests/test_favorability_check.py, src/_gettsim_tests/test_full_taxes_and_transfers.py, src/_gettsim_tests/test_grundrente.py, src/_gettsim_tests/test_grunds_im_alter.py, src/_gettsim_tests/test_kindergeld.py, src/_gettsim_tests/test_kinderzuschl.py, src/_gettsim_tests/test_renten_alter.py, src/_gettsim_tests/test_renten_anspr.py, src/_gettsim_tests/test_soli_st.py, src/_gettsim_tests/test_sozialv_beitr.py, src/_gettsim_tests/test_synthetic.py, src/_gettsim_tests/test_unterhalt.py, src/_gettsim_tests/test_unterhaltsvors.py, src/_gettsim_tests/test_visualizations.py, src/_gettsim_tests/test_vorsorgeaufw.py, src/_gettsim_tests/test_wohngeld.py, src/_gettsim_tests/test_zu_verst_eink.py
Running all tests was quite slow (**6 min 12s** on my machine). This PR should offer a considerable speed increase by caching the results of calls to  `set_up_policy_environment`. Now tests run in **1 min 9s** on my system.
=> test: cache the result of  `set_up_policy_environment`

src/_gettsim_tests/_policy_test_utils.py
* Add a function to filter a `PolicyTestSet` by `test_name` and/or `date`.
* Rename `household_name` to `test_name`.
See also: [Zulip discussion
](https://gettsim.zulipchat.com/#narrow/stream/224837-High-Level-Architecture/topic/tests/near/353133153)
=> Filter `PolicyTestSet`

CHANGES.md, src/_gettsim/social_insurance_contributions/ges_pflegev.py, src/_gettsim/synthetic.py, src/_gettsim/transfers/kindergeld.py, src/_gettsim/transfers/wohngeld.py
#595 added a new input variable, but we forgot to have the input variable created in `synthetic.py`.
=> add anz_eig_kind_bis_24 to synthetic.

CHANGES.md, src/_gettsim/time_conversion.py, src/_gettsim_tests/test_time_conversion.py
Closes #621
No longer create functions for other time units if this leads to a loop. This leads to better error messages, e.g. for the tests from #619:
**Before:** 
```txt
E           ValueError: The DAG contains one or more cycles:
E           
E           [
E               "['eink_selbst_y', 'eink_selbst_m']",
E           ]
```
**After:**
```txt
E           ValueError: The following data columns are missing.
E           
E           [
E               "eink_selbst_m",
E           ]
```
=> fix: don't create functions for other time units if this leads to a cycle in the graph

.pre-commit-config.yaml
I got bitten time and again by messages like this when ruff added a few things:
```
error: TOML parse error at line 49, column 5
|
49 |     "FIX002", # Line contains TODO -- Use stuff from TD area.
|     ^^^^^^^^
Unknown rule selector: `FIX002`
```
Turns out that nbqa-ruff does not automatically update the ruff it uses, which might be different from plain ruff used on Python scripts. This PR makes sure both version are in sync.
=> Pin the dependencies of nbqa (black, ruff) to the same versions used on Python scripts.

.pre-commit-config.yaml, CHANGES.md, CODE_OF_CONDUCT.md, src/_gettsim/functions_loader.py, src/_gettsim/interface.py, src/_gettsim/policy_environment.py, src/_gettsim/taxes/soli_st.py, src/_gettsim/taxes/zu_verst_eink/eink.py, src/_gettsim/visualization.py, src/_gettsim_tests/test_data/full_taxes_and_transfers/2008/hh_id_1.yaml, src/_gettsim_tests/test_full_taxes_and_transfers.py, src/_gettsim_tests/test_soli_st.py, src/_gettsim_tests/test_visualizations.py
Closes #626
Closes partially #378
* Don't load any internal functions implicitly anymore.
* Also load functions that are not time-dependent into the policy environment.
=> fix: don't use functions in `compute_taxes_and_transfers` that are not active

docs/geps/gep-04.md, src/_gettsim/taxes/zu_verst_eink/freibetraege.py
max() and min() are frequently used in the code base, so it would be more uniform to do the same here.
=> Use max() instead of explicit if

CHANGES.md, src/_gettsim/time_conversion.py, src/_gettsim_tests/test_time_conversion.py
Closes #699
Data columns now always overwrite policy functions regardless of their time unit. If, for example, the value `eink_st_y_sn` is needed, and a data column `eink_st_m_sn` and policy function `eink_st_y_sn` are provided, the converted data column is used.
=> Data columns overwrite functions regardless of time unit

CHANGES.md, src/_gettsim/functions_loader.py, src/_gettsim/shared.py, src/_gettsim_tests/test_functions_loader.py
Related to #708
Add a new parameter `is_vectorized` to the `policy_info` decorator to indicate that a function is already vectorized. In that case, it is not vectorized again.
=> Optionally skip vectorization of a policy function

CHANGES.md, src/_gettsim/functions_loader.py, src/_gettsim/shared.py, src/_gettsim/transfers/unterhaltsvors.py, src/_gettsim_tests/test_docs.py, src/_gettsim_tests/test_join.py
Closes #708
Add a `join_numpy` function to make target columns available at the source level. 
The function gets
* Foreign keys,
* Primary keys,
* Targets in the same order as the primary key.
It then maps each foreign key to the associated target. Primary keys must be unique and foreign keys must point to some primary key.
=> Join columns to make target columns available at source level

src/_gettsim/shared.py, src/_gettsim/transfers/unterhaltsvors.py, src/_gettsim_tests/test_join.py
Closes #740
`join_numpy` now takes a value that is used if a foreign key cannot be resolved, e.g. because it is explicitly set to `-1`.
=> fix: fall back to default value if foreign key of `join_numpy` is unresolved

.pre-commit-config.yaml, CHANGES.md, docs/geps/gep-04.md, src/_gettsim/groupings.py, src/_gettsim/interface.py, src/_gettsim/shared.py, src/_gettsim/synthetic.py, src/_gettsim/transfers/arbeitsl_geld.py, src/_gettsim/transfers/arbeitsl_geld_2/kindergelduebertrag.py, src/_gettsim/transfers/unterhaltsvors.py, src/_gettsim/visualization.py, src/_gettsim_tests/test_functions_loader.py, src/_gettsim_tests/test_join.py, src/_gettsim_tests/test_piecewise_polynomial.py, src/_gettsim_tests/test_synthetic.py
- Extract the `float` bit from typing info like `numpy.ndarray[float]`, so we can use proper return types.
- Add array types in some cases
- Enforce convention for importing numpy:
- `np` means our own `numpy_or_jax`
- `numpy` means numpy proper
=> Allow array returns when `skip_vectorization` is being used, enforce import convention.

src/_gettsim/synthetic.py, src/_gettsim_tests/test_synthetic.py
When creating synthetic data, the input variable `p_id_betreuungsk_träger` is currently set to 0 for everyone. I adjusted this to be the same as `p_id_kindergeld_empf`.
=> Add Betreuungskosten pointer to synthetic data.

CHANGES.md, src/_gettsim/transfers/unterhaltsvors.py, src/_gettsim_tests/test_synthetic.py
Closes #733
I let the test run through the years 2017-2024. Extending further back does not work because the Unterhaltsvorschuss isn't implemented prior to 2017 (as discussed in #566). 
I also added a `NotImplementedError` for the Unterhaltsvorschuss until 2016.
Related to #627
=> Test whether `DEFAULT_TARGETS` can be computed with `create_synthetic_data` output

CHANGES.md, src/_gettsim/config.py, src/_gettsim/groupings.py, src/_gettsim/transfers/arbeitsl_geld_2/kindergelduebertrag.py, src/_gettsim_tests/test_data/arbeitsl_geld_2/2024/alleinerz_kein_kindergelduebertrag.yaml, src/_gettsim_tests/test_data/arbeitsl_geld_2/2024/alleinerz_teilw_kindergelduebertrag.yaml, src/_gettsim_tests/test_data/arbeitsl_geld_2/2024/alleinerz_voller_kindergelduebertrag.yaml
=> Remove `eigenbedarf_gedeckt` from Kindergeldübertrag

CHANGES.md, pixi.lock, src/_gettsim/parameters/eink_st.yaml, src/_gettsim/parameters/eink_st_abzuege.yaml, src/_gettsim/taxes/eink_st.py, src/_gettsim_tests/test_data/arbeitsl_geld/2019/hh_id_2.yaml, src/_gettsim_tests/test_data/eink_st/2024/couple_1_child.yaml, src/_gettsim_tests/test_data/eink_st/2024/couple_above_soli_freibetrag.yaml, src/_gettsim_tests/test_data/eink_st/2024/single_above_soli_freibetrag.yaml, src/_gettsim_tests/test_data/eink_st/2024/single_below_soli_freibetrag.yaml
This PR updates income tax parameters and law references for 2024.
Gesetz zur steuerlichen Freistellung des Existenzminimums 2024 has been published: [G. v. 05.12.2024 BGBl. 2024 I Nr. 386](https://www.recht.bund.de/bgbl/1/2024/386/VO.html). New parameter for Grundfreibetrag. New law reference for the full income tax tarif.
Additionally, this PR applies the correct rounding rules for Ehegattensplitting. Before, we only rounded `eink_st_y_sn`. It seems like in practice, there should be some intermediate rounding steps. In particular, in the splitting case, `eink_st_y_sn` should be just the doubled individual income tax which is rounded down.
Note: The parameter file seems to be inconsistent regarding whether the end of the interval or the beginning of the following interval must be used:
- …
=> Update eink_st parameters and rounding rules

src/_gettsim/parameters/kinderzuschl.yaml
This PR updates KiZ parameters and references for 2024 to 2026. In the absence of any overriding law or decree, calculations should follow § 6a (2) based on other parameters.
=> Update KiZ params 2024-2026

CHANGES.md, src/_gettsim/parameters/ges_rente.yaml, src/_gettsim/parameters/sozialv_beitr.yaml
addresses #806 by adding changes to social security contributions and pensions .
To be discussed:
There is no differentiation anymore between East and West Germany with regard to social security and pensions. The easy way (as done here) is to set the `east` and `west` parameter identical henceforth. Alternatively, we could create new functions which ignore the `wohnort_ost` variable.
=> 2025 social security and pension parameters

pixi.lock, src/_gettsim/combine_functions_in_tree.py, src/_gettsim/functions/loader.py, src/_gettsim/interface.py, src/_gettsim/shared.py, src/_gettsim/time_conversion.py, src/_gettsim_tests/test_loader.py, src/_gettsim_tests/test_policy_environment.py, src/_gettsim_tests/test_shared.py
The way we implemented the loading of namespaces in #780 does not quite work. 
We want to have them at the directory level to balance use of namespaces and reducing the amount of qualified names.
=> Change behaviour of namespaces so they are at the module level.

src/_gettsim/interface.py, src/_gettsim_tests/test_rounding.py
Uses the qualified name instead of the leaf name to look for rounding specs in the params file. This is a temporary solution until we have tackled #823.
=> Use qualified name for rounding keys in params files

src/ttsim/compute_taxes_and_transfers.py, src/ttsim/function_types.py, src/ttsim/shared.py, src/ttsim/time_conversion.py, tests/ttsim/test_compute_taxes_and_transfers.py, tests/ttsim/test_shared.py, tests/ttsim/test_time_conversion.py
The top-level namespace did not account for derived functions that are created later. We now add place-holders when creating the top-level namespace for those derived functions.
Because tests don't work currently, I'm not 100% sure that the changes don't crash time conversions (but I'm optimistic that they didn't). Have to keep that in mind if we run into bugs when wrapping up #804.
=> Make top-level namespace include potential derived functions

src/ttsim/combine_functions.py, tests/ttsim/_policy_test_utils.py, tests/ttsim/test_combine_functions.py, tests/ttsim/test_mettsim.py
- Add tests for start and end dates of aggregation by group and p_id
- Fixes a start date/end date bug in aggregation by p_id
- Adds infrastructure for METTSIM tests (but doesn't add test cases yet because tests don't run)
=> Add tests for aggregations and infrastructure for METTSIM testing

src/_gettsim_tests/test_full_taxes_and_transfers.py, src/ttsim/compute_taxes_and_transfers.py, src/ttsim/function_types.py, src/ttsim/typing.py, tests/ttsim/test_compute_taxes_and_transfers.py
We put some effort into trying to convert types. However, the code was a mess and it would be a pain to maintain it. What Python/Pandas/Numpy/Jax do is more than good enough for GETTSIM, too. Now that we have the explicitly annotated `policy_inputs`, it will be easy to check and throw errors if users want to be strict.
This PR removes the code which has been stale for the last week, anyhow.
=> Remove custom type conversions.

src/_gettsim_tests/utils.py, src/ttsim/combine_functions.py, src/ttsim/loader.py, src/ttsim/policy_environment.py, src/ttsim/shared.py, tests/ttsim/mettsim/housing_benefits/eligibility/eligibility.py, tests/ttsim/mettsim/housing_benefits/income/income.py, tests/ttsim/mettsim/inputs.py, tests/ttsim/mettsim/parameters/housing_benefits.yaml, tests/ttsim/mettsim/parameters/payroll_tax.yaml, tests/ttsim/mettsim/payroll_tax/child_tax_credit/child_tax_credit.py, tests/ttsim/mettsim/payroll_tax/child_tax_credit/inputs.py, tests/ttsim/mettsim/payroll_tax/group_by_ids.py, tests/ttsim/mettsim/payroll_tax/income/deductions.py, tests/ttsim/test_combine_functions.py, tests/ttsim/test_data/housing_benefits/2000-01-01/amount_no_children_high_income.yaml, tests/ttsim/test_data/housing_benefits/2000-01-01/amount_no_children_low_income.yaml, tests/ttsim/test_data/housing_benefits/2000-01-01/amount_with_children_high_income.yaml, tests/ttsim/test_data/housing_benefits/2000-01-01/amount_with_children_low_income.yaml, tests/ttsim/test_data/housing_benefits/2025-01-01/amount_no_children_high_income.yaml, tests/ttsim/test_data/housing_benefits/2025-01-01/amount_no_children_low_income.yaml, tests/ttsim/test_data/housing_benefits/2025-01-01/amount_with_children_high_income.yaml, tests/ttsim/test_data/housing_benefits/2025-01-01/amount_with_children_low_income.yaml, tests/ttsim/test_data/payroll_tax/2025-01-01/amount_no_children.yaml, tests/ttsim/test_data/payroll_tax/2025-01-01/amount_with_children.yaml, tests/ttsim/test_data/payroll_tax/2025-01-01/amount_with_children_inputs_need_to_be_converted.yaml, tests/ttsim/test_data/payroll_tax/2025-01-01/group_by_ids.yaml, tests/ttsim/test_docs.py, tests/ttsim/test_visualizations.py, tests/ttsim/utils.py
Add policy test data for METTSIM.
Todo
=> Add test data for METTSIM

docs/rtd_environment.yml, pixi.lock, pyproject.toml, src/ttsim/vectorization.py
In limited set of experiments, it produced exactly the same result. `ast.unparse` is available since Python 3.9, so it's fine to use.
=> Use `ast.unparse` instead of `astor.code_gen.to_source`

src/ttsim/__init__.py, src/ttsim/loader.py, src/ttsim/policy_environment.py, src/ttsim/typing.py, tests/ttsim/test_dates_active.py, tests/ttsim/test_docs.py, tests/ttsim/test_loader.py, tests/ttsim/test_policy_environment.py, tests/ttsim/test_vectorization.py
Update the loader so we first get all objects including module names and original function names. 
Then do checks based on that and filter for active objects in policy environment.
=> Update loader, fixes #830

src/_gettsim/sozialversicherung/geringfügige_einkommen.yaml, src/_gettsim/sozialversicherung/rente/altersrente/entgeltpunkte.py, src/_gettsim/sozialversicherung/rente/altersrente/rentenformel.yaml, src/_gettsim/sozialversicherung/rente/beitrag/arbeitgeberpauschale.yaml, src/_gettsim/sozialversicherung/rente/beitrag/beitrag.py, src/_gettsim_tests/test_data/sozialversicherung/beiträge/1998-01-01/geringfügig_beschäftigt_nur_west.yaml, src/_gettsim_tests/test_data/sozialversicherung/beiträge/1998-01-01/skip_geringfügig_beschäftigt_nur_west.yaml, src/ttsim/policy_environment.py, tests/ttsim/test_policy_environment.py
As realised in #914, we want to be able to interchangeably use parameters and functions with the same leaf name. Use case there:
```
('sozialversicherung', 'rente', 'beitrag', 'beitragsbemessungsgrenze_m')
```
sometimes depends on the data (different values east/west), sometimes it is a common scalar.
Before this PR, this will fail because we check existence of the above path in the `orig_params_tree` against the same path in the `orig_ttsim_objects_tree` without checking for active periods. In this PR, we will adjust the check.
=> Active periods for params

src/_gettsim/sozialversicherung/rente/altersrente/wegen_arbeitslosigkeit/altersgrenze.yaml, src/_gettsim/sozialversicherung/rente/altersrente/wegen_arbeitslosigkeit/wegen_arbeitslosigkeit.py, src/_gettsim_tests/test_groupings.py, src/_gettsim_tests/test_household_links.py, src/ttsim/compute_taxes_and_transfers.py, src/ttsim/plot_dag.py, tests/ttsim/test_compute_taxes_and_transfers.py, tests/ttsim/test_import_version.py
We allow params and columns to be largely interchangeable now. However, when parameters are asked for as targets, we cannot pass them into dags because dags will not look for targets among function inputs.
Solution: In `compute_taxes_and_transfers`, separate `functions_targets` and `params_targets`. Then merge "results" before returning.
=> Allow params as targets

src/_gettsim/sozialversicherung/rente/altersrente/besonders_langjährig/altersgrenze.yaml, src/_gettsim/sozialversicherung/rente/altersrente/für_frauen/altersgrenze.yaml, src/_gettsim/sozialversicherung/rente/altersrente/langjährig/altersgrenze.yaml, src/_gettsim/sozialversicherung/rente/altersrente/regelaltersrente/altersgrenze.yaml, src/_gettsim/sozialversicherung/rente/altersrente/wegen_arbeitslosigkeit/altersgrenze.yaml, src/_gettsim/sozialversicherung/rente/erwerbsminderung/altersgrenze.yaml, src/_gettsim/sozialversicherung/rente/erwerbsminderung/erwerbsminderung.py, src/_gettsim/sozialversicherung/rente/erwerbsminderung/formel.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2001-01-01/teilw_erwerbsgemindert_birthyear_1980_preliminary_products.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2001-01-01/voll_erwerbsgemindert_birthyear_1940_preliminary_products.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2001-01-01/voll_erwerbsgemindert_birthyear_1941_preliminary_products.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2001-01-01/voll_erwerbsgemindert_birthyear_1970_preliminary_products.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2001-01-01/voll_erwerbsgemindert_birthyear_1980_preliminary_products.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2012-01-01/voll_erwerbsgemindert_birthyear_1990_preliminary_products.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2018-01-01/teilw_erwerbsgemindert_birthyear_1995_preliminary_products.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2018-01-01/voll_erwerbsgemindert_birthyear_1960_preliminary_products.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2018-01-01/voll_erwerbsgemindert_birthyear_1970_preliminary_products.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2018-01-01/voll_erwerbsgemindert_birthyear_1980_preliminary_products.yaml, src/_gettsim_tests/test_data/sozialversicherung/rente/erwerbsminderung/2018-01-01/voll_erwerbsgemindert_birthyear_1990_preliminary_products.yaml, src/ttsim/__init__.py, src/ttsim/params-schema.json, src/ttsim/policy_environment.py
Partly fixes #938 
- Apply phase in parameters for EM Rente
- Update the EM Rente parameters for 2000 until 2031
- Add proper references
- Update regression tests: 
- Affects regression tests from 2001 and between 01/2017 and 11/2018 
- 2001: Base Zugangsfaktor calculation on `jahr/monat_renteneintritt` rather than `date_policy_environment`.
- 2017/18: Update policy environment with parameters that were not implemented before (mainly because they never came into effect due to the 11/2018 reform, but we want to include them anyhow).
=> Apply phase in parameters for EM Rente

src/_gettsim/einkommensteuer/abzüge/alter.py, src/_gettsim/einkommensteuer/abzüge/alter.yaml, src/_gettsim/einkommensteuer/einkommensteuer.py, src/_gettsim/kindergeld/kindergeld.py, src/_gettsim/kindergeld/kindergeld.yaml, src/_gettsim/kinderzuschlag/kinderzuschlag.py, src/_gettsim/unterhaltsvorschuss/unterhaltsvorschuss.py
Partly closes the `ConsecutiveInt`-type section of #938 (everything except for `raw_max_miete_m_nach_baujahr`).
To be discussed: Do we want to find a general solution for my provisional implementation of `get_consecutive_int_1d_lookup_table_with_filled_up_tails`? I don't think we need it somewhere else (as of now) so I think dealing with it right there is fine?
=> Apply `ConsecutiveInt`-type to EstG Abzüge and Kindergeld

src/_gettsim/arbeitslosengeld_2/einkommen.py, src/_gettsim/arbeitslosengeld_2/regelbedarf.py, src/_gettsim/einkommensteuer/einkommensteuer.py, src/_gettsim/lohnsteuer/einkommen.py, src/_gettsim/sozialversicherung/minijob.py, tests/ttsim/mettsim/orc_hunting_bounty/orc_hunting_bounty.py
I looked through the whole codebase to find `policy_function`s that should be `param_function`s but found only this one. Also I fixed some import statements and added a `NotImplementedError` for `vorsorgepauschale_y` for Lohnsteuer before 2010.
=> Convert `minijobgrenze_abgeleitet_von_mindestlohn` to params functions.

src/_gettsim/einkommensteuer/zu_versteuerndes_einkommen.py, src/_gettsim/sozialversicherung/beiträge.py, src/_gettsim/sozialversicherung/midijob.py, src/_gettsim/sozialversicherung/rente/altersrente/altersgrenzen.py, src/_gettsim/sozialversicherung/rente/altersrente/altersrente.py, src/_gettsim/sozialversicherung/rente/altersrente/hinzuverdienstgrenzen.py
Replaces absolute with relative paths whenever possible. Closes #849
=> Use relative paths for taxes and transfers

src/ttsim/interface_dag_elements/fail_if.py, tests/ttsim/test_failures.py
Adresses this comment by @hmgaudecker when checking whether the resuls tree can be converted to DF.
```quote
```
=> Check array length when converting to df.

src/_gettsim_tests/test_templates.py, src/ttsim/interface_dag_elements/labels.py, src/ttsim/interface_dag_elements/templates.py, src/ttsim/tt_dag_elements/vectorization.py
Replaces the generic union types that were part of the input dtype template with the correct dtypes derived from `PolicyInput` annotations.
=> Use PolicyInput annotation instead of generic Union type in template

src/_gettsim/erziehungsgeld/erziehungsgeld.py, src/_gettsim/familie/inputs.py, src/ttsim/interface_dag.py, src/ttsim/interface_dag_elements/fail_if.py, src/ttsim/interface_dag_elements/labels.py, src/ttsim/interface_dag_elements/policy_environment.py, src/ttsim/interface_dag_elements/specialized_environment.py, src/ttsim/interface_dag_elements/templates.py, src/ttsim/interface_dag_elements/tt_targets.py, src/ttsim/interface_dag_elements/warn_if.py, tests/ttsim/interface_dag_elements/test_specialized_environment.py, tests/ttsim/mettsim/payroll_tax/child_tax_credit/child_tax_credit.py, tests/ttsim/tt_dag_elements/test_rounding.py
=> Enable annotations for interface / tax-transfer functions

src/_gettsim/einkommensteuer/abzüge/vorsorge.py, src/_gettsim/lohnsteuer/einkommen.py, src/ttsim/interface_dag_elements/__init__.py, src/ttsim/interface_dag_elements/fail_if.py, src/ttsim/testing_utils.py, tests/ttsim/interface_dag_elements/test_failures.py
Closes #999 
Fails if any `param_function` depends on a `ColumnObject`, with the exception being `evaluation_x` and `policy_x` (they are `PolicyInputs`).
=> Fail if ParamFunctions depends on ColumnObjects

CHANGES.md, src/ttsim/tt_dag_elements/vectorization.py, tests/ttsim/tt_dag_elements/test_vectorization.py
It agentic day and I had Cursor take a stab at #869.
@timmens, could you please double-check, also what Marvin writes over there? I was a little surprised that in-place operations worked for him, maybe they only fail in corner cases? Anyhow, they are almost always bad practice and I wouldn't mind prohibiting them if there is an epsilon chance for failure.
With the additional checks, some tests fail. However, I believe they are misguided in the first place in that they contain reduction operations. So they would not make sense with scalar input, which is the case we have in mind for the vectorisation?
=> Raise more errors during vectorization

CHANGES.md, src/gettsim/germany/arbeitslosengeld_2/kindergeldübertrag.py, src/gettsim/germany/bürgergeld/kindergeldübertrag.py, src/gettsim/germany/ids.py
"Twin PR" to https://github.com/ttsim-dev/ttsim/pull/41. Uses the optimized `tt.shared.join` in that PR. 
[**EDIT**: Just realized I need to change this twice, once for "bürgergeld" and once for "arbeitslosengeld_2".]
[**EDIT2**: I added the blocked label because this should only be merged after [ttsim#41](https://github.com/ttsim-dev/ttsim/pull/41) is accepted. It really wouldn't help to use the very inefficient current implementation of `tt.shared.join`. 😅]
[**EDIT3**: Pushed a commit to fix the quadratic memory scaling for JAX, as discussed in https://github.com/ttsim-dev/ttsim/pull/41]
=> Optimize `bürgergeld__in_anderer_bg_als_kindergeldempfänger`

src/gettsim/germany/familie/familie.py
Just a couple of things I noticed while roaming the codebase related to [TTSIM #53](https://github.com/ttsim-dev/ttsim/pull/53).
Not sure about whether `ist_kind_in_einstandsgemeinschaft` is correct as is or it should have more conditions, though? We can leave that corner case for #738 though.
=> Fix a couple of vectorization strategies.
